//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Application Data Directory.
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Button {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory that contains all application data, including configuration files, support files, and logs..
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data Directory.
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Application Log File.
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Button {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the log file in the standard editor..
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of the Database to avoid possible data loss..
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Database Backup.
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_PerformDatabaseBackup_Button {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_PerformDatabaseBackup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup.
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like the application ask you before leave?.
        /// </summary>
        public static string AppConfigurationPage_ExitBehaviorCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Before Exit.
        /// </summary>
        public static string AppConfigurationPage_ExitBehaviorCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the application appearance.
        /// </summary>
        public static string AppConfigurationPage_ThemeCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string AppConfigurationPage_ThemeCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance &amp; Behavior.
        /// </summary>
        public static string AppConfigurationPage_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check System Update.
        /// </summary>
        public static string AppConfigurationPage_VersionCard_PerformSystemUpdate_Button {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_PerformSystemUpdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string AppConfigurationPage_VersionCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available for download. Do you want to download it to the application data directory?.
        /// </summary>
        public static string AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_MessageBox_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_MessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version is the latest..
        /// </summary>
        public static string CheckForUpdateNotification_Success_CurrentVersionUpToDate {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_CurrentVersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available. Download the new version {0} at: {1}.
        /// </summary>
        public static string CheckForUpdateNotification_Success_NewVersionAvailable {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check System Update.
        /// </summary>
        public static string CheckForUpdateNotification_Title {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait as we check for a new version....
        /// </summary>
        public static string CheckForUpdateRequestHandler_NotificationCheckingNewVersion {
            get {
                return ResourceManager.GetString("CheckForUpdateRequestHandler_NotificationCheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ComboBoxItem_Default_Select {
            get {
                return ResourceManager.GetString("ComboBoxItem_Default_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string ControlAppearance_Caution {
            get {
                return ResourceManager.GetString("ControlAppearance_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ControlAppearance_Danger {
            get {
                return ResourceManager.GetString("ControlAppearance_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string ControlAppearance_Info {
            get {
                return ResourceManager.GetString("ControlAppearance_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ControlAppearance_Success {
            get {
                return ResourceManager.GetString("ControlAppearance_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory....
        /// </summary>
        public static string DirectorySelectionBoxImpl_FallbackTitle {
            get {
                return ResourceManager.GetString("DirectorySelectionBoxImpl_FallbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directories....
        /// </summary>
        public static string DirectorySelectionBoxImpl_FallbackTitle_Plural {
            get {
                return ResourceManager.GetString("DirectorySelectionBoxImpl_FallbackTitle_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing system update download....
        /// </summary>
        public static string DownloadUpdateNotification_Starting {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System update download complete. The new file package can be found at: {0}.
        /// </summary>
        public static string DownloadUpdateNotification_Success {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download System Update.
        /// </summary>
        public static string DownloadUpdateNotification_Title {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing system update file to the disk....
        /// </summary>
        public static string DownloadUpdateNotification_WritingFile {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_WritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to retrieve latest release information: {0}.
        /// </summary>
        public static string GetLastestReleaseResponse_Failure_Exception {
            get {
                return ResourceManager.GetString("GetLastestReleaseResponse_Failure_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve latest release information..
        /// </summary>
        public static string GetLastestReleaseResponse_Failure_ReleaseSerialization {
            get {
                return ResourceManager.GetString("GetLastestReleaseResponse_Failure_ReleaseSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Context Initialization Step.
        /// </summary>
        public static string InitializeAppDbContextBootstrapStep_Name {
            get {
                return ResourceManager.GetString("InitializeAppDbContextBootstrapStep_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask before exit?.
        /// </summary>
        public static string MainWindow_CloseHandler_MessageBox_Message {
            get {
                return ResourceManager.GetString("MainWindow_CloseHandler_MessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_CloseHandler_MessageBox_Title {
            get {
                return ResourceManager.GetString("MainWindow_CloseHandler_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MessageBoxIcon_Attention {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxIcon_Error {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBoxIcon_Information {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string MessageBoxIcon_Question {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxIcon_Warning {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup.
        /// </summary>
        public static string PerformDatabaseBackup_TaskRunnerWindow_Title {
            get {
                return ResourceManager.GetString("PerformDatabaseBackup_TaskRunnerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing database backup: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_ExecuteBackup_Failure {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_ExecuteBackup_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup execution finished..
        /// </summary>
        public static string PerformDatabaseBackupNotification_ExecuteBackup_Finish {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_ExecuteBackup_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting database backup execution....
        /// </summary>
        public static string PerformDatabaseBackupNotification_ExecuteBackup_Starting {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_ExecuteBackup_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while preparing the backup file: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Failure {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file preparation execution finished successfully..
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Finish {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting backup file preparation....
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Starting {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup successfully. The file can be found at: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_Success {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup.
        /// </summary>
        public static string PerformDatabaseBackupNotification_Title {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Update.
        /// </summary>
        public static string PerformSystemUpdate_TaskRunnerWindow_Title {
            get {
                return ResourceManager.GetString("PerformSystemUpdate_TaskRunnerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TaskRunnerWindow_Cancel_Button {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TaskRunnerWindow_Close_Button {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_Close_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task runner....
        /// </summary>
        public static string TaskRunnerWindow_Default_Title {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
