//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Diretório da Aplicação.
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório que contêm todos os dados da aplicação, bem como arquivos de configuração, suporte e logs..
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretório de Dados da Aplicação.
        /// </summary>
        public static string AppConfigurationPage_AppDirectoryPathCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_AppDirectoryPathCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Log da Aplicação.
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir o arquivo de log no editor padrão..
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log da Aplicação.
        /// </summary>
        public static string AppConfigurationPage_ApplicationLogCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ApplicationLogCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Backup da Base de Dados.
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie uma cópia da Base de Dados para evitar eventual perda de dados..
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da Base de Dados.
        /// </summary>
        public static string AppConfigurationPage_DatabaseBackupCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_DatabaseBackupCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja que a aplicação sempre pergunte antes de sair?.
        /// </summary>
        public static string AppConfigurationPage_ExitBehaviorCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação ao Sair.
        /// </summary>
        public static string AppConfigurationPage_ExitBehaviorCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ExitBehaviorCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a aparência da aplicação.
        /// </summary>
        public static string AppConfigurationPage_ThemeCard_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema da Aplicação.
        /// </summary>
        public static string AppConfigurationPage_ThemeCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_ThemeCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aparência &amp; Comportamento.
        /// </summary>
        public static string AppConfigurationPage_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Atualização do Sistema.
        /// </summary>
        public static string AppConfigurationPage_VersionCard_Button_Caption {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_Button_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versão Atual.
        /// </summary>
        public static string AppConfigurationPage_VersionCard_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPage_VersionCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma nova versão do sistema está disponível. Deseja executar o download?.
        /// </summary>
        public static string AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_ConfirmDownload_MessageBox_Message {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_ConfirmDownload_MessageBox" +
                        "_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Versão Disponível.
        /// </summary>
        public static string AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_ConfirmDownload_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_ExecuteSystemUpdateAsync_ConfirmDownload_MessageBox" +
                        "_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Backup da Base de Dados.
        /// </summary>
        public static string AppConfigurationPageViewModel_PerformDatabaseBackup_TaskRunnerWindow_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_PerformDatabaseBackup_TaskRunnerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Atualização do Sistema.
        /// </summary>
        public static string AppConfigurationPageViewModel_PerformSystemUpdate_TaskRunnerWindow_Title {
            get {
                return ResourceManager.GetString("AppConfigurationPageViewModel_PerformSystemUpdate_TaskRunnerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja que a aplicação sempre pergunte antes de sair?.
        /// </summary>
        public static string MainWindow_ConfirmApplicationExit_MessageBox_Message {
            get {
                return ResourceManager.GetString("MainWindow_ConfirmApplicationExit_MessageBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair da Aplicação.
        /// </summary>
        public static string MainWindow_ConfirmApplicationExit_MessageBox_Title {
            get {
                return ResourceManager.GetString("MainWindow_ConfirmApplicationExit_MessageBox_Title", resourceCulture);
            }
        }
    }
}
