//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A versão instalada é a mais recente..
        /// </summary>
        public static string CheckForUpdateNotification_Success_CurrentVersionUpToDate {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_CurrentVersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova versão do aplicativo está disponível: {0}.
        /// </summary>
        public static string CheckForUpdateNotification_Success_NewVersionAvailable {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Atualização do Sistema.
        /// </summary>
        public static string CheckForUpdateNotification_Title {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando verificação por nova atualização do sistema....
        /// </summary>
        public static string CheckForUpdateRequestHandler_Starting {
            get {
                return ResourceManager.GetString("CheckForUpdateRequestHandler_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string ComboBoxItemHelper_EmptyComboBoxItem_Content {
            get {
                return ResourceManager.GetString("ComboBoxItemHelper_EmptyComboBoxItem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        public static string ControlAppearance_Caution {
            get {
                return ResourceManager.GetString("ControlAppearance_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string ControlAppearance_Danger {
            get {
                return ResourceManager.GetString("ControlAppearance_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string ControlAppearance_Info {
            get {
                return ResourceManager.GetString("ControlAppearance_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string ControlAppearance_Success {
            get {
                return ResourceManager.GetString("ControlAppearance_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;{0}&apos; attribute..
        /// </summary>
        public static string DiscoverableNavigationViewItemProvider_CreateTuple_Missing_Attribute_Exception {
            get {
                return ResourceManager.GetString("DiscoverableNavigationViewItemProvider_CreateTuple_Missing_Attribute_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando download da nova atualização do sistema....
        /// </summary>
        public static string DownloadUpdateNotification_Starting {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O download da atualização foi concluído. O arquivo está localizando em: {0}.
        /// </summary>
        public static string DownloadUpdateNotification_Success {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Atualização do Sistema.
        /// </summary>
        public static string DownloadUpdateNotification_Title {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravando arquivo de atualização do sistema....
        /// </summary>
        public static string DownloadUpdateNotification_WritingFile {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_WritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha Catastrófica.
        /// </summary>
        public static string ExceptionWarden_MessageBox_Title {
            get {
                return ResourceManager.GetString("ExceptionWarden_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar localizar os novos recursos da versão {0}. Erro: {1}.
        /// </summary>
        public static string FetchNewVersionInformationNotification_Failure {
            get {
                return ResourceManager.GetString("FetchNewVersionInformationNotification_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar os novos recursos..
        /// </summary>
        public static string FetchNewVersionInformationNotification_NotFound {
            get {
                return ResourceManager.GetString("FetchNewVersionInformationNotification_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando localização de novos recursos....
        /// </summary>
        public static string FetchNewVersionInformationNotification_Starting {
            get {
                return ResourceManager.GetString("FetchNewVersionInformationNotification_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos localizados com sucesso!.
        /// </summary>
        public static string FetchNewVersionInformationNotification_Success {
            get {
                return ResourceManager.GetString("FetchNewVersionInformationNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizar Recursos da Nova Versão.
        /// </summary>
        public static string FetchNewVersionInformationNotification_Title {
            get {
                return ResourceManager.GetString("FetchNewVersionInformationNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar diretório....
        /// </summary>
        public static string FileSystemDialog_OpenDirectory_Fallback_Title {
            get {
                return ResourceManager.GetString("FileSystemDialog_OpenDirectory_Fallback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar diretórios....
        /// </summary>
        public static string FileSystemDialog_OpenDirectory_Fallback_Title_Plural {
            get {
                return ResourceManager.GetString("FileSystemDialog_OpenDirectory_Fallback_Title_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar arquivo....
        /// </summary>
        public static string FileSystemDialog_OpenFile_Fallback_Title {
            get {
                return ResourceManager.GetString("FileSystemDialog_OpenFile_Fallback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar arquivos....
        /// </summary>
        public static string FileSystemDialog_OpenFile_Fallback_Title_Plural {
            get {
                return ResourceManager.GetString("FileSystemDialog_OpenFile_Fallback_Title_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar arquivo....
        /// </summary>
        public static string FileSystemDialog_OpenSave_Fallback_Title {
            get {
                return ResourceManager.GetString("FileSystemDialog_OpenSave_Fallback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível deserializar as informações do último release..
        /// </summary>
        public static string GetLastestReleaseResponse_DeserializationFailure_Message {
            get {
                return ResourceManager.GetString("GetLastestReleaseResponse_DeserializationFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar recuperar as informações do último release. Erro: {0}.
        /// </summary>
        public static string GetLastestReleaseResponse_Failure_Message {
            get {
                return ResourceManager.GetString("GetLastestReleaseResponse_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível deserializar as informações de recursos da release..
        /// </summary>
        public static string GetReleaseAssetsResponse_DeserializationFailure_Message {
            get {
                return ResourceManager.GetString("GetReleaseAssetsResponse_DeserializationFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar recuperar as informações de recursos da release. Erro: {0}.
        /// </summary>
        public static string GetReleaseAssetsResponse_Failure_Message {
            get {
                return ResourceManager.GetString("GetReleaseAssetsResponse_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string MessageDialogIcon_Attention {
            get {
                return ResourceManager.GetString("MessageDialogIcon_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string MessageDialogIcon_Error {
            get {
                return ResourceManager.GetString("MessageDialogIcon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string MessageDialogIcon_Information {
            get {
                return ResourceManager.GetString("MessageDialogIcon_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questão.
        /// </summary>
        public static string MessageDialogIcon_Question {
            get {
                return ResourceManager.GetString("MessageDialogIcon_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        public static string MessageDialogIcon_Warning {
            get {
                return ResourceManager.GetString("MessageDialogIcon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page element must be a FrameworkElement type..
        /// </summary>
        public static string NavigationViewPageProvider_GetPage_Must_FrameworkElement_Exception {
            get {
                return ResourceManager.GetString("NavigationViewPageProvider_GetPage_Must_FrameworkElement_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create &apos;{0}&apos; instance..
        /// </summary>
        public static string TaskRunnerBuilder_CreateTaskRunnerWindow_Unregistered_Window_Exception {
            get {
                return ResourceManager.GetString("TaskRunnerBuilder_CreateTaskRunnerWindow_Unregistered_Window_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string TaskRunnerWindow_CancelButton_Caption {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_CancelButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string TaskRunnerWindow_CloseButton_Caption {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_CloseButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executando Tarefa....
        /// </summary>
        public static string TaskRunnerWindow_Title {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuro.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto Contraste.
        /// </summary>
        public static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
