//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A versão instalada é a mais recente..
        /// </summary>
        public static string CheckForUpdateNotification_Success_CurrentVersionUpToDate {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_CurrentVersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uma nova versão (v{0}) disponível em: {1}.
        /// </summary>
        public static string CheckForUpdateNotification_Success_NewVersionAvailable {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Success_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Atualização do Sistema.
        /// </summary>
        public static string CheckForUpdateNotification_Title {
            get {
                return ResourceManager.GetString("CheckForUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando verificação por nova atualização do sistema....
        /// </summary>
        public static string CheckForUpdateRequestHandler_Starting {
            get {
                return ResourceManager.GetString("CheckForUpdateRequestHandler_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string ComboBoxItem_Default_Select_Display_Text {
            get {
                return ResourceManager.GetString("ComboBoxItem_Default_Select_Display_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        public static string ControlAppearance_Caution {
            get {
                return ResourceManager.GetString("ControlAppearance_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string ControlAppearance_Danger {
            get {
                return ResourceManager.GetString("ControlAppearance_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string ControlAppearance_Info {
            get {
                return ResourceManager.GetString("ControlAppearance_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string ControlAppearance_Success {
            get {
                return ResourceManager.GetString("ControlAppearance_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o diretório....
        /// </summary>
        public static string DirectorySelectionBoxImpl_FallbackTitle {
            get {
                return ResourceManager.GetString("DirectorySelectionBoxImpl_FallbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os diretórios....
        /// </summary>
        public static string DirectorySelectionBoxImpl_FallbackTitle_Plural {
            get {
                return ResourceManager.GetString("DirectorySelectionBoxImpl_FallbackTitle_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando download da nova atualização do sistema....
        /// </summary>
        public static string DownloadUpdateNotification_Starting {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O download da atualização foi concluído. O arquivo está localizando em: {0}.
        /// </summary>
        public static string DownloadUpdateNotification_Success {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Atualização do Sistema.
        /// </summary>
        public static string DownloadUpdateNotification_Title {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravando arquivo de atualização do sistema....
        /// </summary>
        public static string DownloadUpdateNotification_WritingFile {
            get {
                return ResourceManager.GetString("DownloadUpdateNotification_WritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to retrieve the latest release information. Error: {0}.
        /// </summary>
        public static string GitHubHttpClient_GetLastestReleaseAsync_Exception {
            get {
                return ResourceManager.GetString("GitHubHttpClient_GetLastestReleaseAsync_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível deserializar as informações de release..
        /// </summary>
        public static string GitHubHttpClient_GetLastestReleaseAsync_Release_Serialization_Failure {
            get {
                return ResourceManager.GetString("GitHubHttpClient_GetLastestReleaseAsync_Release_Serialization_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        public static string MessageBoxIcon_Attention {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string MessageBoxIcon_Error {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string MessageBoxIcon_Information {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questão.
        /// </summary>
        public static string MessageBoxIcon_Question {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        public static string MessageBoxIcon_Warning {
            get {
                return ResourceManager.GetString("MessageBoxIcon_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string TaskRunnerWindow_CancelButton_Caption {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_CancelButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string TaskRunnerWindow_CloseButton_Caption {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_CloseButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executando Tarefa....
        /// </summary>
        public static string TaskRunnerWindow_Default_Title {
            get {
                return ResourceManager.GetString("TaskRunnerWindow_Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuro.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto Contraste.
        /// </summary>
        public static string Theme_HighContrast {
            get {
                return ResourceManager.GetString("Theme_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
