//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nameless.WPF.Client.Sqlite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nameless.WPF.Client.Sqlite.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializar Contexto da Base de Dados.
        /// </summary>
        public static string InitializeDbContextBootstrapStep_Name {
            get {
                return ResourceManager.GetString("InitializeDbContextBootstrapStep_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao executar o backup dos dados da base de dados. Erro: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_BackupDatabase_Failure {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_BackupDatabase_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup dos dados da base de dados concluído..
        /// </summary>
        public static string PerformDatabaseBackupNotification_BackupDatabase_Finish {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_BackupDatabase_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando o backup dos dados da base de dados....
        /// </summary>
        public static string PerformDatabaseBackupNotification_BackupDatabase_Starting {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_BackupDatabase_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a preparação do arquivo de backup da base de dados. Erro: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Failure {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparação do arquivo de backup da base de dados concluído..
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Finish {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando a preparação do arquivo de backup da base de dados....
        /// </summary>
        public static string PerformDatabaseBackupNotification_PrepareBackupFile_Starting {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_PrepareBackupFile_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup da base de dados concluído com sucesso. O arquivo pode ser encontrado em: {0}.
        /// </summary>
        public static string PerformDatabaseBackupNotification_Success {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar Backup da Base de Dados.
        /// </summary>
        public static string PerformDatabaseBackupNotification_Title {
            get {
                return ResourceManager.GetString("PerformDatabaseBackupNotification_Title", resourceCulture);
            }
        }
    }
}
